# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e958f86e7353cdc5b3eb60923a1ecdd0c1349a7fd413934da55a4a69909d023461e78d867a029e22000959dc036d381bed0a52d0e89cd28da40f4a1135fb71b3
  aws:
    access_key: <%= ENV["AWS_API_KEY"] %>
    secret_key: <%= ENV["AWS_API_SECRET"] %>
    bucket: tinypixelgame
    s3_region: us-east-1
  unity:
    cloud_api_key: <%= ENV["UNITY_CLOUD_KEY"] %>

test:
  secret_key_base: 7d85a3d6ddb961fc36f013df72a3083fe20a86d8b641593a88ca592ec3960422f29ddaab80253b0c104b237989bac4fc72e0f0f2e90725a0aeb7975347707518

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  aws:
    access_key: <%= ENV["AWS_API_KEY"] %>
    secret_key: <%= ENV["AWS_API_SECRET"] %>
    bucket: tinypixelgame
    s3_region: us-east-1
  unity:
    cloud_api_key: <%= ENV["UNITY_CLOUD_KEY"] %>
